challengessupport/config/routes.rb
Rails.application.routes.draw do

  get '/', to: redirect('/challenges')

  resources :challenges do
    resources :supports
  end

end

challengessupport/app/models/challenge.rb
class Challenge < ActiveRecord::Base
	mount_uploader :poster, PosterUploader

	has_many :supports

	validates :title, {presence: true}
	validates :description, {presence: true}

end

challengessupport/app/models/support.rb
class Support < ActiveRecord::Base
	belongs_to :challenge

	validates :mail, {presence: true,
					  uniqueness: true,
				      format: {with: /\A[a-zA-Z0-9]*@{1}[a-zA-Z]*\.{1}[a-zA-Z]{2,3}\z/} }

end

challengessupport/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 	#el problema de este filtro es que cada vez que creas una acción nueva tienes que pensar si 
 	#necesitas o no la query, por temas de rendimiento
	before_filter :last_challenges

  	def last_challenges
		@last_challenges = Challenge.order("created_at DESC").limit(3)
	end

end

challengessupport/app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

	PER_PAGE = 10

	def index

		if params[:key_word].present?
			key_word = "%#{params[:key_word]}%"
			@challenges = Challenge.where("title ilike ?", key_word)
			@page = 1
		elsif params[:page]
			@challenges = Challenge.limit(PER_PAGE).offset( (params[:page].to_i-1)*PER_PAGE )
			@page = params[:page].to_i
		else
			@challenges = Challenge.all
			@page = 1
		end

	end

	def show
		@challenge = Challenge.find_by(id: params[:id])
		@support = @challenge.supports.new
	end

	def new
		@challenge = Challenge.new
	end

	def create
		@challenge = Challenge.new entry_params
		@challenge.save
		redirect_to challenges_path
	end

	def edit
		@challenge = Challenge.find params[:id]
	end

	def update

		@challenge = Challenge.find params[:id]

		if @challenge.update_attributes entry_params
			flash[:notice] = "challenge updated succesfully"
			redirect_to challenge_path(@challenge.id)
		else
			flash.now[:error] = "error updating challenge"
			render 'edit'
		end

	end

	#strong parameters
	private
	def entry_params
		params.require(:challenge).permit(:title, :description, :poster)
	end


end

challengessupport/app/controllers/supports_controller.rb
class SupportsController < ApplicationController

	def create

		@challenge = Challenge.find_by(id: params[:challenge_id])
		@support = @challenge.supports.new entry_params

		if @support.save entry_params
			flash[:notice] = "thx for support"
			SupportMailer.new_support(@challenge, @support).deliver
			redirect_to challenge_path(@challenge.id)
		else
			flash.now[:error] = "fatal error"
			render 'challenges/show'
		end

	end

	#strong parameters
	def entry_params
		params.require(:support).permit(:mail)
	end

end

challengessupport/app/helpers/application_helper.rb
module ApplicationHelper

	def flash_message
		if flash[:error]
			content_tag :div, class: 'message alert' do
				content_tag :p do flash[:error] end
			end
		elsif flash[:notice]
			content_tag :div, class: 'message notice' do
				content_tag :p do flash[:notice] end
			end
		end
	end
	
end

challengessupport/app/helpers/challenges_helper.rb
module ChallengesHelper


	def previous_page?
		if params[:page].blank? || params[:page].to_i == 1
			false
		else
			true
		end
	end



end

challengessupport/app/helpers/supports_helper.rb
module SupportsHelper
end

challengessupport/app/views/challenges/edit.html.erb
<%= flash_message %>

<%= form_for [@challenge] do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<br>
	<%= f.label :description %>
	<%= f.text_field :description %>
	<br>

	<%= f.submit 'Save' %>
<% end %>

challengessupport/app/views/challenges/index.html.erb
<h1> Support some of our challenges! </h1>
<ul>
	<% @challenges.each do |challenge| %>
		<li> 
			Title: <%= link_to(challenge.title, challenge_path(challenge.id)) %> - Description: <%= challenge.description %> -
			<%= link_to("Edit challenge", edit_challenge_path(challenge.id)) %>
		</li>
	<% end %>
</ul>


<% if previous_page? %>
	<%= link_to('← Anterior', challenges_path(page: params[:page].to_i-1)) %>
<% end %>

<%= link_to('Siguiente →', challenges_path(page: params[:page].to_i+1)) %>



<h1> ... or create one! </h1>

<%= link_to("New Challenge!", new_challenge_path) %>

<h1> search the challenges </h1>


    <%= form_tag challenges_path, method: :get, class: "pure-form" do %>
      <%= search_field_tag :key_word, params[:key_word], placeholder: "Search challenges" %>
    <% end %>

challengessupport/app/views/challenges/new.html.erb
	<%= form_for [@challenge], html: {multipart: true} do |f| %>

		<%= f.label :title %>
		<%= f.text_field :title %>
		<br>
		<%= f.label :description %>
		<%= f.text_field :description %>
		<br>
		<%= f.label :poster %>
		<%= f.file_field :poster %>
		<br>	


		<%= f.submit 'Save' %>
	<% end %>

challengessupport/app/views/challenges/show.html.erb
<p>
Title: <%= @challenge.title %>
<br>
Image: <%= image_tag @challenge.poster.url %>
<br>
Description: <%= @challenge.description %> 
</p>

<br>
<br>
<br>


<%= flash_message %>

<%= form_for [@challenge, @support] do |f| %>
	<%= f.label :mail %>
	<%= f.text_field :mail %>
	<br>
	<%= f.submit 'Save' %>
<% end %>

<p>
Num supporters: <%= @challenge.supports.count %>
</p>

<br>
<br>

<p>
<%= link_to("challenges list", challenges_path) %>
</p>

challengessupport/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Challengessupport</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<div>
	<h3> Last created challenges </h3>
	<ul>
		<% @last_challenges.each do |challenge| %>
			<li> <%=link_to challenge.title, challenge_path(challenge) %> </li>
		<% end %>
	</ul>
</div>



</body>
</html>